trigger:
  - dev

pool:
  vmImage: ubuntu-latest

variables:
  - name: REACT_APP_REDIRECT_TO
    value: https://ambitious-sand-025fb710f.azurestaticapps.net/
steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: 'build'
      api_location: 'api'
    env:
      azure_static_web_apps_api_token: $(deployment_token)
      REACT_APP_REDIRECT_TO: $(REACT_APP_REDIRECT_TO)
