name: Dev build and Deploy

trigger:
  - dev

variables:
  group: Secrets

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
    displayName: Checkout code

- task: CmdLine@2
  inputs:
    script: |
      sudo mv $(constants.dev) $(constants.dev.file.path)
      cat $(constants.dev.file.path)

  - task: Bash@3
    displayName: Build
    inputs:
      targetType: 'inline'
      script: |        
        npm install 
        npm run build
    env:
      REACT_APP_REDIRECT_TO: $(REACT_APP_REDIRECT_TO)

  - task: AzureStaticWebApp@0
    displayName: Deploy
    inputs:
      app_location: '/'
      output_location: 'build'
      api_location: 'api'
    env:
      azure_static_web_apps_api_token: $(deployment_token)