trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: ''
      api_location: ''
    env:
      azure_static_web_apps_api_token: $(deployment_token)